### PR TITLE
Fix for all deprecation warnings

### PR DESCRIPTION
**Pull request by d4rkr00t**

### CODE REVIEW

**Comment by lbaehren** [comment]
Anybody still maintaining the theme? I was running into the same set of deprecated warnings as I now found in this patch. How do we make this available to the rest of the world?

**Comment by d4rkr00t** [comment]
Hi @lbaehren i don't use this theme anymore, so maybe more deprecation warnings have appeared after  i made this fix.

**Comment by lbaehren** [comment]
Thanks for the info @d4rkr00t - the thing is that I am still quite fond of the theme, so I decided to create a fork and start working on the changes.

**Comment by notslang** [comment]
merged via ad644bf?

**Pull request closed without merging**
